const iconElement=document.querySelector()
const tempElement=document.querySelector()
const descElement=document.querySelector()
const locationElement=document.querySelector()
const notificationElement=document.querySelector()
